language:
  node_js
script:
  - npm run test:coverage
node_js:
    - '6'
    - '8'
    - '10'
    - '12'
install:
  - npm i
  - npm i -g codecov
after_success:
  - npm run report-coverage
  - npm run success
notifications:
  email:
    recipients:
    - weronika.biala@atos.net
    on_success: always
    on_failure: always