language:
  node_js
node_js:
    - '6'
    - '8'
    - '10'
    - '12'
after_success:
  - npm run success
notifications:
  email:
    recipients:
    - weronika.biala@atos.net
    on_success: always
    on_failure: always